package com.example.demo.Enums;

public enum AuditActions {
    UPLOAD_VOTERS,
    UPLOAD_CANDIDATES,
    BATCH_FAILED,
    BATCH_COMPLETED,
    OPEN_ELECTION,
    CLOSE_ELECTION,
    PUBLISH_ELECTION,
    VOTE_CAST,
    CREATE_ELECTION,
    UPDATE_ELECTION,
    STOP_ELECTION,
    START_ELECTION,
    VOTER_VERIFICATION,
    CREATE_ORGANIZATION,
    ISSUE_ONETIME_TOKEN,
    CONSUME_ONETIME_TOKEN,
    VALIDATE_ONETIME_TOKEN,
    USER_REGISTRATION,
    ACCESS_ELECTION,
    USER_LOGIN,
    CREATE_USER
}
