spring.application.name=${SPRING_APPLICATION_NAME:demo}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
keycloak.base-url=${KEYCLOAK_BASE_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database=${SPRING_JPA_DATABASE:postgresql}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
management.metrics.tags.application=${MANAGEMENT_METRICS_TAGS_APPLICATION:${spring.application.name}}

logging.pattern.level=${LOGGING_PATTERN_LEVEL:%5p}
logging.pattern.console=${LOGGING_PATTERN_CONSOLE:%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n}

logging.level.com.example.demo=${LOGGING_LEVEL_COM_EXAMPLE_DEMO:INFO}
logging.level.org.springframework=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}
logging.level.org.hibernate=${LOGGING_LEVEL_ORG_HIBERNATE:WARN}
logging.level.io.micrometer.tracing=${LOGGING_LEVEL_IO_MICROMETER_TRACING:INFO}
logging.level.org.springframework.boot.actuate.autoconfigure.tracing=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_ACTUATE_AUTOCONFIGURE_TRACING:INFO}
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
logging.level.org.springframework.security.web.FilterChainProxy=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_FILTERCHAINPROXY:WARN}
logging.level.org.springframework.security.web.authentication.AnonymousAuthenticationFilter=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_AUTHENTICATION_ANONYMOUSAUTHENTICATIONFILTER:WARN}
logging.level.org.springframework.boot.actuate=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_ACTUATE:INFO}

spring.batch.job.enabled=${SPRING_BATCH_JOB_ENABLED:false}
spring.batch.jdbc.initialize-schema=${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA:always}
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99

receipt.token.secret=${RECEIPT_TOKEN_SECRET}
loki.url=${LOKI_URL:}