spring.profiles.active=prod

server.forward-headers-strategy=framework

logging.level.com.example.demo=${LOGGING_LEVEL_COM_EXAMPLE_DEMO:INFO}
logging.level.org.springframework=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}
logging.level.org.hibernate=${LOGGING_LEVEL_ORG_HIBERNATE:WARN}
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://trustvote.live,https://www.trustvote.live}