spring.application.name=demo

# Keycloak (dev: published to your laptop)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/OVS-System
keycloak.base-url=http://localhost:8081
keycloak.realm=OVS-System
keycloak.client-id=ovs_frontend

# App DB (published to your laptop)
spring.datasource.url=jdbc:postgresql://localhost:5433/ovsApp
spring.datasource.username=ovsApp
spring.datasource.password=ovsPass

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Actuator + Prometheus scrape
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

## ? TRACING (Spring Boot / Micrometer way)
#management.tracing.enabled=true
#management.tracing.sampling.probability=1.0
#
## ? Export traces to Tempo (OTLP HTTP)
#management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
#management.otlp.tracing.transport=http


# (optional) nice level pattern in console for quick check
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]

# Logging levels
logging.level.com.example.demo=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# Debug exporter if needed
logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.boot.actuate.autoconfigure.tracing=DEBUG

# Kill Prometheus scrape/security spam
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.FilterChainProxy=WARN
logging.level.org.springframework.security.web.authentication.AnonymousAuthenticationFilter=WARN
logging.level.org.springframework.boot.actuate=INFO

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.docker.compose.enabled=false

# ? create *_bucket metrics for latency
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99

# optional but helpful
receipt.token.secret=shahed12345@
loki.url=http://localhost:3100/loki/api/v1/push
